//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insurance_Claims
{
    using System;
    using System.Collections.Generic;
    
    public partial class Claim
    {
        public int Id { get; set; }
        public string Reference { get; set; }
        public int LossAdjusterId { get; set; }
        public string Policy { get; set; }
        public System.DateTime LossDate { get; set; }
        public int LossTypeId { get; set; }
        public string LossLoc { get; set; }
        public bool Closed { get; set; }
        public Nullable<System.DateTime> ClosedDate { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
        public int LastUpdatedId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedId { get; set; }
    
        public virtual LossType LossType { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
    }
}
