//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insurance_Claims
{
    using System;
    using System.Collections.Generic;
    
    public partial class Email
    {
        public int Id { get; set; }
        public int LegacyActivityId { get; set; }
        public string RecipientTo { get; set; }
        public string Subject { get; set; }
        public string BodyText { get; set; }
        public string SentBy { get; set; }
        public Nullable<System.DateTime> SentTime { get; set; }
        public string PartyTypeCode { get; set; }
    }
}
